appname = Rides_gateway
httpport = 7000
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 
authenticationBaseUrl = http://localhost:7080
customerBaseUrl = http://localhost:7083
itemBaseUrl = http://localhost:7082
systemBaseUrl = http://localhost:7880
transactionsBaseUrl = http://localhost:7085
auditTrailBaseUrl = http://localhost:7091
notificationsBaseUrl = http://localhost:7090
paymentBaseUrl = http://localhost:7088
# imagesBaseUrl = "/Users/bedeabbe/Desktop/projects/golang/images"
imagesBaseUrl = "/usr/app/images"
branchManagerRoleName = "Branch Manager"
managingDirectorRoleName = "Managing Director"
superAdminRoleName = "SUPER_ADMIN"
salesProductType = "Sales"
rentalsProductType = "Rentals"
# salesProductType = "Male"
# rentalsProductType = "Female"
# branchManagerRoleName = "Customer Service Checker"
